version: 0.2

env:
  secrets-manager:
    AZURE_CLIENT_ID: azure-deploy-creds:AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET: azure-deploy-creds:AZURE_CLIENT_SECRET
    AZURE_TENANT_ID: azure-deploy-creds:AZURE_TENANT_ID

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing Azure CLI..."
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  build:
    commands:
      - dotnet restore
      - dotnet build --configuration Release
      - dotnet publish -c Release -o ./publish

  post_build:
    commands:
      - echo "Zipping artifact..."
      - cd publish && zip -r ../app.zip . && cd ..

      - echo "Logging into Azure..."
      - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - echo "Deploying to Azure App Service..."
      - az webapp deploy --resource-group Target-Demo --name Target-Demo-Final --src-path ./app.zip --type zip

artifacts:
  files:
    - '**/*'
  base-directory: publish
